export const docsIndex = [
  { title: 'Oversikt', href: '/use/oversikt', description: 'Plattform-oversikt og nøkkelbegreper', category: 'general' },
  { title: 'For brukere', href: '/use/bruker', description: 'Brukerveiledning: kjøp, kurs og opptak', category: 'user' },
  { title: 'For administratorer', href: '/use/admin', description: 'Admin arbeidsflyter, sikkerhet og beste praksis', category: 'admin' },
  { title: 'Teknisk', href: '/use/teknisk', description: 'Arkitektur, RLS, utviklerarbeidsflyt', category: 'developer' },
  { title: 'API & Integrasjoner', href: '/use/api', description: 'Endepunkter, autentisering, eksempler', category: 'developer' },
  { title: 'Migrasjoner', href: '/use/migrasjoner', description: 'SQL-migrasjonsregler og testing', category: 'developer' },
  { title: 'Deploy & Drift', href: '/use/deployment', description: 'CI, miljø og monitoring', category: 'developer' },
  { title: 'Funksjoner', href: '/use/funksjoner', description: 'Booking, seatmap, betalinger', category: 'general' },
  { title: 'FAQ', href: '/use/faq', description: 'Ofte stilte spørsmål', category: 'general' },
  { title: 'Komponenter', href: '/use/components', description: 'UI components and patterns', category: 'developer' },
  { title: 'Layout', href: '/use/layout', description: 'Header, Footer, App Layout and theme tokens', category: 'developer' },
  { title: 'Supabase', href: '/use/supabase', description: 'Supabase helpers, admin vs server clients and RLS patterns', category: 'developer' },
  { title: 'Scripts', href: '/use/scripts', description: 'Migration scripts and developer utilities', category: 'developer' },
  { title: 'Testing & CI', href: '/use/testing', description: 'How to run tests and CI workflow', category: 'developer' },
  { title: 'Design', href: '/use/design', description: 'Design tokens and component guidelines', category: 'general' },
  { title: 'Payments', href: '/use/payments', description: 'Payment gateways, webhooks and setup', category: 'general' },
  { title: 'Server patterns', href: '/use/server', description: 'App Router notes and route handler patterns', category: 'developer' },
  { title: 'Security', href: '/use/security', description: 'Secrets, RLS and policies', category: 'developer' },
  { title: 'Seatmap', href: '/use/seatmap', description: 'Seat map types and locking', category: 'general' },
  { title: 'How To', href: '/use/how-to', description: 'How-to guides: order tickets, create shows, connect PayPal', category: 'general' },
  { title: 'Dokumentasjonsindeks', href: '/use/indeks', description: 'Søk og naviger i dokumentasjonen', category: 'general' },
]
